# Generated by Django 5.0rc1 on 2023-11-30 02:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0.0)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
