# Generated by Django 5.0rc1 on 2023-12-12 21:41

import application.finance.enum
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_value_expense_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('UNKNOWN', 'unknown'), ('SAT_SP', 'sat_sp'), ('NFCE_SP', 'nfce_sp')], default=application.finance.enum.CouponType['UNKNOWN'], max_length=20)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
