# Generated by Django 5.0rc1 on 2023-12-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.coupon'),
        ),
    ]
